Loop until success in renew-sk-secret-script
Added an infinite loop to retry getting credentials, and error-checking. This avoids sk-api getting into an infinite loop of its own, from which it can't recover, when sk-secret is bad. The result is more robustness when sk-api starts before the vault or while the vault is sealed.

diff --git a/playbooks/roles/skadmin/templates/kube/renew-sk-secret/renew-sk-secret-script b/playbooks/roles/skadmin/templates/kube/renew-sk-secret/renew-sk-secret-script
--- a/playbooks/roles/skadmin/templates/kube/renew-sk-secret/renew-sk-secret-script
+++ b/playbooks/roles/skadmin/templates/kube/renew-sk-secret/renew-sk-secret-script
@@ -1,11 +1,45 @@
 #!/bin/bash
 
-export KUBE_TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`
-export KUBE_NAMESPACE=`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`
+while :
+do
+  VAULT_SECRETID=`curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/auth/approle/role/sk/secret-id | jq -r .data.secret_id`
+  if [ $? -ne 0 ]; then
+    echo "jq filtering of VAULT_SECRETID failed"
+    sleep 10
+    continue
+  fi
+  VAULT_ROLEID=`curl -s -X GET -H "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/auth/approle/role/sk/role-id | jq -r .data.role_id`
+  if [ $? -ne 0 ]; then
+    echo "jq filtering of VAULT_ROLEID failed"
+    sleep 10
+    continue
+  fi
 
-VAULT_SECRETID=`curl -s -X POST -H "X-Vault-Token: $VAULT_TOKEN" {{skadmin_vault_url}}/v1/auth/approle/role/sk/secret-id | jq -r .data.secret_id`
-VAULT_ROLEID=`curl -s -X GET -H "X-Vault-Token: $VAULT_TOKEN" {{skadmin_vault_url}}/v1/auth/approle/role/sk/role-id | jq -r .data.role_id`
+  # no error but no secret_id either?  If so curl must have failed
+  if [ "x${VAULT_SECRETID}" == "xnull" ] || [ "x${VAULT_SECRETID}" == "x" ]; then
+    echo "bad secret_id"
+    sleep 10
+    continue
+  fi
+  
+  # no error but no role_id either?  If so curl must have failed
+  if [ "x${VAULT_ROLEID}" == "xnull" ] || [ "x${VAULT_ROLEID}" == "x" ];  then
+    echo "bad role_id"
+    sleep 10
+    continue
+  fi
 
-kubectl delete secret tapis-sk-vault-secrets
-kubectl create secret generic tapis-sk-vault-secrets --from-literal=vault-secretid=$VAULT_SECRETID --from-literal=vault-roleid=$VAULT_ROLEID
+  # replace kubernetes secret
+  kubectl delete secret tapis-sk-vault-secrets
+  # ignore error if secret didn't exist
+  
+  kubectl create secret generic tapis-sk-vault-secrets --from-literal=vault-secretid=$VAULT_SECRETID --from-literal=vault-roleid=$VAULT_ROLEID
+  if [ $? -ne 0 ]; then
+    echo "creating secret failed"
+    sleep 10
+    continue
+  fi
 
+  # getting here means we successfully replaced the secret with a well-formed one, so we're done
+  break
+done
